export default function TermsOfService({ onBack }) {
  return (
    <div className="legal-page">
      <button className="btn-back" onClick={onBack}>← Back</button>
      <div className="legal-inner">
        <h1>Terms of Service</h1>
        <p className="legal-date">Last updated: April 27, 2025</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using Bedtime Stories, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>
        </section>

        <section>
          <h2>2. The Service</h2>
          <p>Bedtime Stories provides AI-generated personalised children's stories. Stories are generated using the Anthropic Claude API and are intended for children aged 2–12. We reserve the right to modify or discontinue the service at any time.</p>
        </section>

        <section>
          <h2>3. User Accounts</h2>
          <ul>
            <li>You must sign in with a valid Google account to use the service.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must not share your account with others.</li>
            <li>You must be at least 18 years old to create an account and purchase credits.</li>
          </ul>
        </section>

        <section>
          <h2>4. Credits & Payments</h2>
          <ul>
            <li>Credits are required to generate stories (1 credit per story) and for voice playback (2 credits per session).</li>
            <li>Credits are non-transferable and cannot be exchanged for cash.</li>
            <li>All payments are processed securely by Razorpay.</li>
            <li>Prices are displayed in Indian Rupees (INR) and are inclusive of applicable taxes.</li>
            <li>Credits do not expire.</li>
          </ul>
        </section>

        <section>
          <h2>5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Attempt to generate harmful, abusive, or illegal content</li>
            <li>Reverse engineer, scrape, or abuse the service</li>
            <li>Share, sell, or resell generated stories for commercial purposes without written permission</li>
            <li>Use the service in any way that violates applicable laws</li>
          </ul>
        </section>

        <section>
          <h2>6. Intellectual Property</h2>
          <p>Stories generated by the service are provided for personal, non-commercial use. Addinfi retains no ownership over the content of generated stories. The service's interface, design, and code are owned by Addinfi.</p>
        </section>

        <section>
          <h2>7. Disclaimer of Warranties</h2>
          <p>The service is provided "as is" without warranties of any kind. We do not guarantee that AI-generated content will always be accurate, appropriate, or error-free, though we implement safety guardrails to ensure child-appropriate content.</p>
        </section>

        <section>
          <h2>8. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Addinfi shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
        </section>

        <section>
          <h2>9. Governing Law</h2>
          <p>These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.</p>
        </section>

        <section>
          <h2>10. Contact</h2>
          <p>For questions about these terms: <a href="mailto:legal@addinfi.com">legal@addinfi.com</a></p>
        </section>
      </div>
    </div>
  )
}
